name: CI

on:
  pull_request:
    branches: [ master ]

    workflow_dispatch:

env:
  JAVA_VERSION: 1.15

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -user: actions/setup-java@v1.4.3
      with:
        java-version: ${{ env.JAVA_VERSION }}
          - name: Build with Maven
            run: mvn -B clean test